name: Django Test with PostgreSQL Example

on:
    workflow_call:
    workflow_dispatch:
    push:
      branches: [main]
    pull_request:
        branches: [main]

jobs:
  test:
    name: Run Custom user model tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13  # Adjust PostgreSQL version as needed
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432  # Expose PostgreSQL port

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      
      - name: Install requirements
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      - name: Prepare database
        run: |
          python manage.py migrate --noinput
      
      - name: Run tests
        run: |
            python manage.py test users/tests

      - name: Collect test artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: |
            users/tests/test_results
