name: Tests with PostgreSQL

on:
    workflow_call:
    workflow_dispatch:
    push:
      branches: [main]
    pull_request:
        branches: [main]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      
      - name: Install requirements
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      - name: Prepare database
        run: |
          python manage.py migrate --noinput
      
      - name: Run tests
        run: |
            python manage.py test
