name: Tests with PostgreSQL

on:
    workflow_call:
    workflow_dispatch:
    push:
      branches: [main]
    pull_request:
        branches: [main]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      
      - name: Install requirements
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      - name: Prepare database
        run: |
          python manage.py migrate --noinput
      
      - name: Run tests
        env:
          POSTGRES_DB: "nzksrilc"
          POSTGRES_USER: "nzksrilc"
          POSTGRES_PASSWORD: "TzaqUbD8aDjDgacJBQlAx8q-l8iio11M"
          POSTGRES_HOST: "bubble.db.elephantsql.com"
        run: |
            python manage.py test
